---
- name: Install python-venv
  become_user: root
  become: true
  ansible.builtin.apt:
    name:
      - python3-venv

- name: Create python venv
  ansible.builtin.pip:
    virtualenv: "{{ ansible_venv }}"
    name:
      - ansible

- name: Run playbook in pull-mode
  ansible.builtin.shell: source "{{ ansible_venv }}/bin/activate" && ansible-pull -U "{{ pull_repo | mandatory }}" "{{ pull_playbook }}"
  register: pull_output
  changed_when: pull_output.rc != 0
